version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: source/docker/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:17
    container_name: db
    restart: always
    ports:
      - "5434:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "7777:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
