"""Fix coin columns non negative

Revision ID: b0e00b5023df
Revises: 9fca6d6d0b02
Create Date: 2025-02-15 15:12:35.430517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e00b5023df'
down_revision: Union[str, None] = '9fca6d6d0b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coin_amount', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('user', 'coint_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coint_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'coin_amount')
    # ### end Alembic commands ###
